### ISSUE TITLE
A little help

### ISSUE THREAD

**Issue by saymoncoppi** [xexpanderx/Fluxbox-themes#1]
Hello buddy!
I realy like your themes, congratulations!!!
Im tryng to learn how to make my own based on:
- Window styles and GTK:
https://b00merang.weebly.com/windows-10.html
- Dock:
regular: http://www.omgubuntu.co.uk/2017/04/system76-pop-gtk-theme-ubuntu
transparency: https://vinceliuice.deviantart.com/art/Azure-Gtk-Theme-512327812

could you gimme some tips like were can I start?

**Comment by xexpanderx** [comment]
Hello!

I would start by choosing a WM of my taste which is fairly easy to customize, for example any *box will work.

After deciding the WM, I usually start to focus on the WM theme. When deciding how to combine the colors, I usually use a wallpaper as a template. I move on with the GTK2 theme, trying to match that with the wallpaper as well as with the WM theme e.t.c.

I believe the WM and GTK2 theme is a great start, focus on those until you get a feeling of it, especially GTK2 theming. By "feeling", I mean getting to know how to code in GTK2 and WM in such a way that the colors and ui are "perfectly" matched. In addition, you change the icons, fonts, dock panels e.t.c.

When you have mastered it, one can move on to the next step; theming GTK3 and QT5. GTK3 and QT are difficult to master (~5000 lines of code), so it is a good way to have a feeling for the "colors" before starting with those two beasts.

Good luck and thank you!

**Comment by saymoncoppi** [comment]
Hey tks!

Im still interested on how can I make the Taskbar like the samples. Usings
just icons instead of icons and text (default from fluxbox), fixing one
icon as a launcher and make the switcher for desktops like yours.

Do you know wich parameters at the theme file I have to modify? In fact id
like to make somwthing like deepin efficient Taskbar or Windows 10
original. Could you help me?

Tks buddy, best regards

Em 30/01/2018 12:10, "xexpanderx" <notifications@github.com> escreveu:

**Comment by xexpanderx** [comment]
Hi,

You can't use launchers in toolbar, at least not by default. In theory, a script for launching softwares could be incorporated in the systemtray area, but I never did it myself.

Showing only icons in toolbar is possible, by using the same font color as the bg color for toolbar. Although, icon rendering is really ugly in toolbar so I would not recommend it. The fluxbox toolbar is pretty limited in that sense.
