### ISSUE TITLE
Changing the iconbar item width in Fluxbox

### ISSUE THREAD

**Issue by LoganDark** [xexpanderx/Fluxbox-themes#2]
Hey, thank you for these awesome themes! I'm currently using a modified version of WFlux, and it looks really good:

![2022-07-07-075131_3840x2160_scrot](https://user-images.githubusercontent.com/4723091/177803902-f9202428-9333-4f9d-8240-6046bed467b1.png)

One issue I'm having is that I can't seem to increase the width of the iconbar items (at the bottom). They're all super cramped and not wide enough. Increasing the width of the pixbuf isn't working. :(

Is there any way to get them to be wider? I've tried looking all over the internet but I can't find any setting to put in the `theme.cfg`. `man fluxbox-style` has nothing about width or anything like that.

**Comment by xexpanderx** [comment]
Hi!

I think you have to change it in the "init" file and the parameter "session.screen0.iconbar.iconWidth". That should set the width of the iconbar items if I remember correctly.

**Comment by xexpanderx** [comment]
In order to activate it, you need to have at least this in your init:

```
session.screen0.iconbar.iconWidth: 128
session.screen0.iconbar.alignment: Left
```

And then you can play around with iconWidth.

**Comment by LoganDark** [comment]
Thank you, that fixed it! <3

**Comment by LoganDark** [comment]
In the future, is there a "better" place I could go to ask for Fluxbox/Blackbox theming help? Asking you personally feels kinda rude :p

**Comment by xexpanderx** [comment]
I don't know of any place like that :). You could try the reddit forum for Fluxbox: https://www.reddit.com/r/fluxbox/
